spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        sql: warn
        type:
          descriptor:
            sql:
              BasicBinder: warn
    root: info

server:
  port: 8081
